services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=https://api.indianupscgpt.com/
    ports:
      - "4001:8080"
    volumes:
      - .:/app